# Generated by Django 5.0.6 on 2026-06-07 19:20

import content.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='OG-изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (ЧПУ)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_or_photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='Логотип или фото')),
                ('website_url', models.URLField(blank=True, verbose_name='Официальный сайт')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Благополучатель',
                'verbose_name_plural': 'Благополучатели',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='OG-изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (ЧПУ)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
                'ordering': ['sort_order', '-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='OG-изображение')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (ЧПУ)')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateField(verbose_name='Дата')),
                ('source_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('is_from_vk', models.BooleanField(default=False, verbose_name='Импортировано из VK')),
                ('vk_post_id', models.CharField(blank=True, max_length=100, verbose_name='ID поста VK')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['sort_order', '-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='Изображение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'verbose_name_plural': 'Изображения новостей',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('goals', models.TextField(blank=True, verbose_name='Цели')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('footer_documents_text', models.TextField(blank=True, verbose_name='Текст документов в футере')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Информация об организации',
                'verbose_name_plural': 'Информация об организации',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='OG-изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (ЧПУ)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='Логотип')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт партнёра')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='OG-изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (ЧПУ)')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('status', models.CharField(choices=[('upcoming', 'Скоро'), ('registration_open', 'Идёт регистрация'), ('registration_closed', 'Регистрация закрыта'), ('finished', 'Прошёл')], default='upcoming', max_length=32, verbose_name='Статус')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('location_text', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='races/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='Обложка')),
                ('russian_running_url', models.URLField(blank=True, verbose_name='Ссылка на регистрацию')),
                ('results_url', models.URLField(blank=True, verbose_name='Ссылка на результаты')),
                ('rules_url', models.URLField(blank=True, verbose_name='Ссылка на правила')),
                ('route_url', models.URLField(blank=True, verbose_name='Ссылка на маршрут')),
                ('external_info_url', models.URLField(blank=True, verbose_name='Доп. внешняя ссылка')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Забег',
                'verbose_name_plural': 'Забеги',
                'ordering': ['sort_order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='RaceDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(help_text='Например: "5 км"', max_length=100, verbose_name='Дистанция')),
                ('age_category', models.CharField(blank=True, help_text='Например: "18+" или "детский забег"', max_length=100, verbose_name='Возрастная категория')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Дистанция забега',
                'verbose_name_plural': 'Дистанции забегов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='Изображение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.gallery', verbose_name='Фотоальбом')),
            ],
            options={
                'verbose_name': 'Изображение фотоальбома',
                'verbose_name_plural': 'Изображения фотоальбомов',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(condition=models.Q(('is_from_vk', True)), fields=('vk_post_id',), name='unique_vk_post_id'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='race',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='races', to='content.beneficiary', verbose_name='Благополучатели'),
        ),
        migrations.AddField(
            model_name='race',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='races', to='content.partner', verbose_name='Партнёры'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='content.race', verbose_name='Забег'),
        ),
        migrations.AddField(
            model_name='racedistance',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='content.race', verbose_name='Забег'),
        ),
    ]
