# Generated by Django 5.0.6 on 2026-06-07 19:42

import content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Например: "2 111 503 ₽"', max_length=100, verbose_name='Значение')),
                ('label', models.CharField(help_text='Например: "Собрано для помощи"', max_length=255, verbose_name='Подпись')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения (Наше влияние)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Роль / должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), content.validators.ImageSizeValidator()], verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='about',
            field=models.TextField(blank=True, verbose_name='История / О нас'),
        ),
    ]
