# Generated by Django 5.0.6 on 2026-06-09 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_achievement_teammember_organizationinfo_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (ЧПУ)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата отчёта')),
                ('document', models.FileField(blank=True, help_text='Необязательно. Можно загрузить файл и/или указать внешнюю ссылку ниже.', null=True, upload_to='reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Файл отчёта (PDF и т.п.)')),
                ('external_url', models.URLField(blank=True, help_text='Необязательно. Ссылка на отчёт во внешнем сервисе.', verbose_name='Внешняя ссылка на отчёт')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('race', models.ForeignKey(blank=True, help_text='Необязательно. Если отчёт относится к конкретному забегу.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='content.race', verbose_name='Связанный забег')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['sort_order', '-date', '-created_at'],
            },
        ),
    ]
